[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_error"
restartPolicyMaxRetries = 10
